[project]
name = "Gleaner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "YifanYang6", email = "YifanYang6@link.cuhk.edu.cn" }
]
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.5",
    "polars>=1.31.0",
    "rcabench-platform==0.4.1",
]
license = "MPL-2.0"
[build-system]
requires = ["uv_build>=0.7.12,<0.8.0"]
build-backend = "uv_build"

[tool.pyright]
exclude = [ #
    ".git",
    "**/__pycache__",
    ".venv",
    ".vscode",
    ".idea",
    "data/",
    "output/",
    "temp/",
]

[tool.uv.sources]
rcabench-platform = { path = "platform/rcabench-platform", editable = true }

[tool.uv.workspace]
members = [
    "third_party/Nezha",
    "third_party/ShapleyIQ",
]
exclude = ["third_party/TracePicker"]

[dependency-groups]
dev = [ #
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.7",
    "marimo[recommended]>=0.14.10",
    "kubernetes-stubs-elephant-fork>=33.1.0",
    "plotly>=6.2.0",
    "pyqt6>=6.9.1",
    "pyright>=1.1.403",
    "ruff>=0.12.2",
    "vegafusion>=2.0.2",
    "vl-convert-python>=1.8.0",
    "pandas-stubs>=2.3.0.250703",
    "uv-bump>=0.1.2",
    "scalene>=1.5.54",
]
